[package]
  cjc-version = "1.0.0"
  version = "0.1.0"
  name = "jinguissl_aes_bench"
  output-type = "executable"
  src-dir = "src"
  compile-option = "-Woff unused"
  description = "jinguiSSL AES benchmark"

[dependencies]
  [dependencies.jinguissl]
    path = "../.."
